//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace yhz.Dashboard.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ElementRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ElementRes() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("yhz.Dashboard.Resources.ElementRes", typeof(ElementRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Need data source 的本地化字符串。
        /// </summary>
        public static string data_support {
            get {
                return ResourceManager.GetString("data_support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Default 的本地化字符串。
        /// </summary>
        public static string default_value {
            get {
                return ResourceManager.GetString("default_value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Element Type 的本地化字符串。
        /// </summary>
        public static string list_title {
            get {
                return ResourceManager.GetString("list_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Creation Time 的本地化字符串。
        /// </summary>
        public static string model_creation_time {
            get {
                return ResourceManager.GetString("model_creation_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Data config 的本地化字符串。
        /// </summary>
        public static string model_data_config {
            get {
                return ResourceManager.GetString("model_data_config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Data name 的本地化字符串。
        /// </summary>
        public static string model_data_name {
            get {
                return ResourceManager.GetString("model_data_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Description 的本地化字符串。
        /// </summary>
        public static string model_des {
            get {
                return ResourceManager.GetString("model_des", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Element type 的本地化字符串。
        /// </summary>
        public static string model_element_type {
            get {
                return ResourceManager.GetString("model_element_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Name 的本地化字符串。
        /// </summary>
        public static string model_name {
            get {
                return ResourceManager.GetString("model_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No. 的本地化字符串。
        /// </summary>
        public static string model_no {
            get {
                return ResourceManager.GetString("model_no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Code 的本地化字符串。
        /// </summary>
        public static string para_code {
            get {
                return ResourceManager.GetString("para_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit parameter 的本地化字符串。
        /// </summary>
        public static string para_edit {
            get {
                return ResourceManager.GetString("para_edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Name 的本地化字符串。
        /// </summary>
        public static string para_name {
            get {
                return ResourceManager.GetString("para_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Parameter Script 的本地化字符串。
        /// </summary>
        public static string para_script {
            get {
                return ResourceManager.GetString("para_script", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Preview 的本地化字符串。
        /// </summary>
        public static string preview {
            get {
                return ResourceManager.GetString("preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Auto refresh 的本地化字符串。
        /// </summary>
        public static string preview_auto_refresh {
            get {
                return ResourceManager.GetString("preview_auto_refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Data source 的本地化字符串。
        /// </summary>
        public static string preview_data_config {
            get {
                return ResourceManager.GetString("preview_data_config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ID 的本地化字符串。
        /// </summary>
        public static string preview_identification {
            get {
                return ResourceManager.GetString("preview_identification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Interval 的本地化字符串。
        /// </summary>
        public static string preview_interval {
            get {
                return ResourceManager.GetString("preview_interval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Parameter(json) 的本地化字符串。
        /// </summary>
        public static string preview_paras {
            get {
                return ResourceManager.GetString("preview_paras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Terminal 的本地化字符串。
        /// </summary>
        public static string preview_terminal {
            get {
                return ResourceManager.GetString("preview_terminal", resourceCulture);
            }
        }
    }
}
