//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace yhz.Dashboard.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TerminalRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TerminalRes() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("yhz.Dashboard.Resources.TerminalRes", typeof(TerminalRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Terminal 的本地化字符串。
        /// </summary>
        public static string list_title {
            get {
                return ResourceManager.GetString("list_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Creation Time 的本地化字符串。
        /// </summary>
        public static string model_creation_time {
            get {
                return ResourceManager.GetString("model_creation_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dashboard 的本地化字符串。
        /// </summary>
        public static string model_dashboard {
            get {
                return ResourceManager.GetString("model_dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Description 的本地化字符串。
        /// </summary>
        public static string model_des {
            get {
                return ResourceManager.GetString("model_des", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Disabled 的本地化字符串。
        /// </summary>
        public static string model_forbidden {
            get {
                return ResourceManager.GetString("model_forbidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Identification 的本地化字符串。
        /// </summary>
        public static string model_identification {
            get {
                return ResourceManager.GetString("model_identification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IP 的本地化字符串。
        /// </summary>
        public static string model_ip {
            get {
                return ResourceManager.GetString("model_ip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Name 的本地化字符串。
        /// </summary>
        public static string model_name {
            get {
                return ResourceManager.GetString("model_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No. 的本地化字符串。
        /// </summary>
        public static string model_no {
            get {
                return ResourceManager.GetString("model_no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Parameter JSON 的本地化字符串。
        /// </summary>
        public static string model_para {
            get {
                return ResourceManager.GetString("model_para", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cycle(s) 的本地化字符串。
        /// </summary>
        public static string model_playcycle {
            get {
                return ResourceManager.GetString("model_playcycle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Order 的本地化字符串。
        /// </summary>
        public static string model_playorder {
            get {
                return ResourceManager.GetString("model_playorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Theme 的本地化字符串。
        /// </summary>
        public static string model_theme {
            get {
                return ResourceManager.GetString("model_theme", resourceCulture);
            }
        }
    }
}
